import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Link from "next/link";
import Image from "next/image";
import NavList from '@/components/NavList';
import { Button } from "@/components/ui/button";
import { Heart } from "lucide-react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function Sidebar() {
  return (
    <div className="pb-12 w-1/5 bg-gray-200 dark:bg-neutral-900">
      <div className="space-y-4 py-4">
        <div className="px-3 py-2">
          <Button
            asChild
            variant="ghost"
            className="w-full justify-start flex gap-2"
          >
            <Link href="/gallery">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                fill="none"
                viewBox="0 0 24 24"
                strokeWidth={1.5}
                stroke="currentColor"
                className="w-6 h-6 font-bold"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  d="M2.25 15.75l5.159-5.159a2.25 2.25 0 013.182 0l5.159 5.159m-1.5-1.5l1.409-1.409a2.25 2.25 0 013.182 0l2.909 2.909m-18 3.75h16.5a1.5 1.5 0 001.5-1.5V6a1.5 1.5 0 00-1.5-1.5H3.75A1.5 1.5 0 002.25 6v12a1.5 1.5 0 001.5 1.5zm10.5-11.25h.008v.008h-.008V8.25zm.375 0a.375.375 0 11-.75 0 .375.375 0 01.75 0z"
                />
              </svg>
              Gallery
            </Link>
          </Button>
          <Button
            asChild
            variant="ghost"
            className="w-full justify-start flex gap-2"
          >
            <Link href="/favorites">
              <Heart />
              Favorites
            </Link>
          </Button>
        </div>
      </div>
    </div>
  )
}



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="border-b border-gray-400">
            <div className="flex h-16 items-center px-4 container mx-2">
              <Link href='/' className="flex items-center gap-2">
                <Image
                  src="/logo.jpeg"
                  width={40}
                  height={40}
                  alt="PixelVault Logo"
                  className="rounded-full"
                />
                <span className="text-[26px] font-extrabold">PixelVault</span>
              </Link>
              <NavList />
            </div>
          </div>
          <div className="flex">
            <Sidebar />
            <div className="w-4/5 px-4 pt-8">
              {children}
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
